package com.liuzhi.eschool.constants

class UrlConstans{
    companion object {
        val BaseUrl="http://47.98.126.71:8006"

        val FirstType= "$BaseUrl/front/firstType"
        val SecondType= "$BaseUrl/front/lsTypeSecond"
        val LessonSelective= "$BaseUrl/front/getLessonSelective"
        val LessonDetail= "$BaseUrl/front/getLessonDetail"
        val Login= "$BaseUrl/login"
        val ProjectColumn= "$BaseUrl/front/getProjectColumn"
        val ColInfo= "$BaseUrl/front/getColInfo"
        val AllProject= "$BaseUrl/front/getAllProject"
        val ProjectInfoCol= "$BaseUrl/front/getProjectInfoCol"
        val InformationByCol= "$BaseUrl/front/getInformationByCol"
        val ImgCodeGet= "$BaseUrl/register"
        val Register= "$BaseUrl/reg"
        val ForgotMail= "$BaseUrl/forgot"
        val ForgotPassword= "$BaseUrl/editPassword"
        val OnlineExamList= "$BaseUrl/front/getOnlineExamList"
        val SimulateExamList= "$BaseUrl/front/getSimulateExamList"
        val SurveyList= "$BaseUrl/front/getSurveyList"
        val CurrentUser= "$BaseUrl/front/getCurrentUser"
        val ForumList= "$BaseUrl/front/getForumList"
        val CourseList= "$BaseUrl/front/getCourseList"
        val MyWorkList= "$BaseUrl/front/getMyWorkList"
        val FinishWorkList= "$BaseUrl/front/getFinishWorkList"
        val UserHistory= "$BaseUrl/center/userhistory"
        val Collection= "$BaseUrl/center/usercollection"
        val ChatList= "$BaseUrl/front/getChatList"
        val ScheduleList= "$BaseUrl/front/getScheduleList"
        val UserCenter= "$BaseUrl/center/usercenter"
        val PaperTypeList= "$BaseUrl/front/getPaperTypeList"
        val PersonalGradeList= "$BaseUrl/front/getPersonalGradeList"
        val LessonDetailById= "$BaseUrl/front/getLessonDetail"
        val LessonCollect= "$BaseUrl/center/lessonCollect"
        val GetForum= "$BaseUrl/front/idGetForum"
        val UserPost= "$BaseUrl/center/userpost"
    }
}